// ============================================================
//  RESOURCES — embaralhados a cada visita.
//
//  Categorias: "referencias" | "tutoriais" | "processo"
//  Tipo: auto-detectado pela URL (YouTube = vídeo, resto = link)
//        Para imagens ou downloads, adicione: type: "image" | "download"
//
//  Para adicionar novos recursos, cole aqui no array abaixo.
// ============================================================

const RESOURCES = [

  // ── Referências ──────────────────────────────────────────────
  {
    cat: "referencias",
    title: "Lay’s Chip Cam with David Beckham & Thierry Henry",
    url: "https://www.youtube.com/watch?v=LLJ38OdS_q8",
    description: "Comercial da Lay's no estádio com Beckham e Thierry Henry quebrando a quarta parede pra falar com a câmera. Vale pela comédia improvisada, timing de reação e como a campanha integra naturalidade de celebridade e cena de torcida.",
    tags: ["publicidade", "direção"],
  },
  {
    cat: "referencias",
    title: "Defy // On Spec Ad // Sony Venice + Sony FX3 + Freefly Ember",
    url: "https://www.youtube.com/watch?v=w0PkvfJ-uBg",
    description: "Spec ad de 30s da Tenfold para a On, rodado em 1 dia com Sony Venice, FX3 e drone Freefly Ember nas Cooke S4. Referência de comercial esportivo: ritmo, movimento de câmera e textura de imagem.",
    tags: ["publicidade", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "ArrDee - Different ft. The Shapeshifters",
    url: "https://www.youtube.com/watch?v=6meAaX907to",
    description: "Videoclipe do rapper britânico ArrDee em parceria com The Shapeshifters. Produção visual densa e bem construída.",
    tags: ["videoclipe", "direção"],
  },
  {
    cat: "processo",
    title: "COMO PRODUZIMOS 4 REELS PARA UM RESTAURANTE EM 1 DIA SÓ",
    url: "https://www.youtube.com/watch?v=T70A0yeBNLU",
    description: "Produção acelerada de conteúdo: como planejar e executar 4 reels para um cliente em um único dia de gravação.",
    tags: ["produção", "behind the scenes", "processo criativo"],
  },
  {
    cat: "referencias",
    title: "Cinematic Fashion Film - Beyond Space (Sony Venice + Leica R)",
    url: "https://www.youtube.com/watch?v=xKha-MXPKTQ",
    description: "Fashion film cinematográfico com combinação de Sony Venice e lentes Leica R. Estética limpa e atmosfera forte.",
    tags: ["fashion film", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "Sempre Forza Ferrari",
    url: "https://www.youtube.com/watch?v=rvpD9e-wPBk",
    description: "Filme de marca da Ferrari na F1, montagem rápida no ritmo da paixão dos pilotos. Vale pela direção cinematográfica, color em torno do vermelho e edição que costura depoimento e ação de pista.",
    tags: ["publicidade", "direção", "edição"],
  },
  {
    cat: "referencias",
    title: "Young Miko - WASSUP",
    url: "https://www.youtube.com/watch?v=LEhTlLnOVDU",
    description: "Videoclipe oficial de Young Miko. Visual arrojado com referências de estética latina contemporânea.",
    tags: ["videoclipe", "direção"],
  },
  {
    cat: "referencias",
    title: "NEMZZZ - PTSD",
    url: "https://www.youtube.com/watch?v=oojBNXKtE9M",
    description: "Videoclipe oficial do NEMZZZ pra faixa PTSD, do mixtape Do Not Disturb. Vale assistir como referência de direção e estética de clipe de rap UK em formato curto, pouco mais de 2 minutos.",
    tags: ["videoclipe", "direção", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "Kidwild - Redemption Ft. Nemzzz",
    url: "https://www.youtube.com/watch?v=MYHrk_6qky8",
    description: "Videoclipe de rap UK dirigido por donprod e dinperlis. Vale como referência de direção e iluminação em locação, com styling cuidado e visual coeso pra peça curta de 2:37.",
    tags: ["videoclipe", "direção", "iluminação"],
  },
  {
    cat: "referencias",
    title: "The Next Chapter: The first US female fitness athlete of Red Bull",
    url: "https://www.youtube.com/watch?v=i0KBwYzivmc",
    description: "Atleta de fitness da Red Bull conta em primeira pessoa como a pressão por ranking virou crise de saúde mental, a pausa de um ano e o reencontro com o esporte. Vale pela perspectiva sobre carreira e propósito.",
    tags: ["documentário", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "Interplanetary Criminal - No Time (feat. Sadboi)",
    url: "https://www.youtube.com/watch?v=XVzxU5HNwtk",
    description: "Videoclipe oficial com estética visual marcante, na linha dos outros UK artists da coleção.",
    tags: ["videoclipe", "direção"],
  },
  {
    cat: "referencias",
    title: "adidas Backyard Legends: The Greatest Football Story Ever Told",
    url: "https://www.youtube.com/watch?v=mJJY53qhJe0",
    description: "Curta de 5 min que conta um 3 contra 3 de rua como lenda urbana, narrada no carro a caminho do jogo. Vale pelo roteiro cômico, ritmo de diálogo e direção de elenco com Chalamet, Messi, Bellingham, Lamine Yamal e Trinity Rodman.",
    tags: ["publicidade", "direção", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "Chasing Sub 2: The Journey of Sabastian Sawe’s Historic 1:59:30 Marathon",
    url: "https://www.youtube.com/watch?v=qRr0lmYvp5g",
    description: "Filme de marca da adidas sobre Sabastian Sawe quebrando as 2h na maratona de Londres 2026. Vale pela fotografia, ritmo de montagem e construção emocional de um doc esportivo de orçamento alto, dos bastidores íntimos ao clímax da prova.",
    tags: ["documentário", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "Ibeyi - Aset",
    url: "https://www.youtube.com/watch?v=XwxA_oOzMDY",
    description: "Clipe da Ibeyi rodado em Cuba por Corry Van Rhijn e Roman Pichon Herrera, fotografia de Luis Armando Arteaga. Vale pela direção que mistura percussão e dança ao vivo com pipeline pesado de VFX e arte em IA. Referência de integração entre captação real e pós.",
    tags: ["videoclipe", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "GENER8ION - STORM starring Yung Lean",
    url: "https://www.youtube.com/watch?v=x6_mbnsh6VU",
    description: "Videoclipe experimental dirigido por Romain Gavras com coreografia de Damien Jalet. Atmosfera distópica, coreografia coletiva intensa, cinematografia impecável.",
    tags: ["videoclipe", "cinematografia", "direção"],
  },

  {
    cat: "referencias",
    title: "NEMZZZ - GASS feat. Travis Scott",
    url: "https://www.youtube.com/watch?v=veav1xL-NAc",
    description: "Clipe oficial de rap UK com Travis Scott, menos de dois minutos. Serve como referência de videoclipe de performance, com corte colado no beat e a cena sustentada pela presença dos artistas em quadro.",
    tags: ["videoclipe","direção","edição"],
  },

  // ── Tutoriais ────────────────────────────────────────────────
  {
    cat: "tutoriais",
    title: "How to animate maps like VOX (After Effects Tutorial)",
    url: "https://www.youtube.com/watch?v=8Xxxd7me-oc",
    description: "Monta uma animação de mapa estilo VOX no After Effects com um rig de câmera 3D controlado por nulls (controllers de rotação X, Y, Z e posição via pick-whip parenting), além de profundidade de campo com abertura alta, renderer 3D clássico e motion blur.",
    tags: ["after effects", "motion design"],
  },
  {
    cat: "tutoriais",
    title: "A Simple Guide to Depth of Field",
    url: "https://www.youtube.com/watch?v=34jkJoN8qOI",
    description: "Explica profundidade de campo do zero e os três controles práticos: distância até o sujeito, distância focal e abertura (f-stop). Mostra como cada um abre ou fecha o foco e a lógica invertida da escala de f-stop.",
    tags: ["cinematografia"],
  },
  {
    cat: "tutoriais",
    title: "What is Dynamic Range?",
    url: "https://www.youtube.com/watch?v=FTXMx8ij_Nw",
    description: "Explica o que define o alcance dinâmico do sensor: full well capacity e noise floor, por que os stops úteis variam entre RED e ARRI, como a curva gama (log vs padrão) limita a imagem final e por que ISO nativo importa fora do RAW.",
    tags: ["cinematografia"],
  },
  {
    cat: "tutoriais",
    title: "Color Spaces: Explained from the Ground Up",
    url: "https://www.youtube.com/watch?v=99v96TL-tuY",
    description: "Explica espaço de cor do zero: o que é cor, metamerismo, como os cones LMS viram o CIE 1931 XYZ, e por que Rec.709, DCI-P3 e Rec.2020 são RGB absolutos que só mudam os pontos primários. Bom pra entender o que rola por baixo do color grading.",
    tags: ["color grading"],
  },
  {
    cat: "tutoriais",
    title: "Teoria da cor",
    url: "https://www.youtube.com/watch?v=VbJtLQPj4go",
    description: "Introdução à teoria da cor pra pintura digital: os três atributos (valor, matiz, saturação), o círculo cromático como simplificação de um espaço 3D, cores complementares, mistura de pigmento vs navegação digital e o gamut mask do James Gurney.",
    tags: ["color grading"],
  },
  {
    cat: "tutoriais",
    title: "The Amazing Math behind Colors!",
    url: "https://www.youtube.com/watch?v=gnUYoQ1pwes",
    description: "Explica a ciência da cor do zero: resposta dos cones, espaços LMS e CIE 1931, diagrama de cromaticidade, gamut, cubo RGB, conversão pra HSV e hex, e como telas RGB e impressoras CMYK formam cada cor.",
    tags: ["color grading"],
  },
  {
    cat: "tutoriais",
    title: "Hide Your Audio Cuts With This Method in DaVinci Resolve",
    url: "https://www.youtube.com/watch?v=d2RRrqNzmWg",
    description: "Como cortar áudio de entrevista nas consoantes surdas (p, t, k, s, f), que não têm pitch e soam sempre iguais, pra emendas invisíveis. Inclui o truque de defasar o corte de vídeo do corte de áudio pra esconder a junção. Serve em qualquer editor.",
    tags: ["davinci resolve", "áudio", "edição"],
  },
  {
    cat: "processo",
    title: "How the 'Severance' Editor Cut the Finale Like a Music Video",
    url: "https://www.youtube.com/watch?v=eGkfByNEcw0",
    description: "Geoffrey Richman destrincha decisões de montagem do finale de Severance: empilhar takes em tracks paralelos pra comparar selects, usar a banda marcial como trilha contínua, construir ritmo com cortes rápidos e parada seca, e deslocar o POV pra emoção ficar só no Mark.",
    tags: ["análise", "edição", "behind the scenes"],
  },
  {
    cat: "tutoriais",
    title: "Beat the Compression! How to Get Better YouTube Uploads",
    url: "https://www.youtube.com/watch?v=DI1BjkmVhTg",
    description: "Gerald Undone testa o que sobrevive à compressão do YouTube: super-sharpen leve no export, H.264 em vez de H.265/AV1, MP4, bitrate variável até 45 Mbps em 4K, sem quantizer (Constant QP), e evitar gradientes escuros e cenas dark.",
    tags: ["produção", "edição"],
  },
  {
    cat: "tutoriais",
    title: "Mastering Skin Tones with Balance DCTL for DaVinci Resolve",
    url: "https://www.youtube.com/watch?v=_wpinhILzgg",
    description: "Walkthrough do Balance DCTL (Utility DCTL pack do Mononodes) no DaVinci Resolve: indicador de tom de pele que marca desvios em magenta/verde, slider de ângulo de matiz, mapas de calor de exposição e saturação, e o botão gray out non-skin para focar na pele.",
    tags: ["davinci resolve", "color grading"],
  },
  {
    cat: "processo",
    title: "Inside the Live Session: Billie Eilish’s ‘BIRDS OF A FEATHER’ with Mixer Aron Forbes",
    url: "https://www.youtube.com/watch?v=5CgR3UH1txU",
    description: "Aron Forbes destrincha o mix da vocal ao vivo da Billie Eilish e mostra cada plugin Waves no trabalho: Clarity Vx pra matar o vazamento da bateria no microfone, C4 multibanda pra encaixar os backing vocals atrás dela, S1 pra alargar as harmonias e F6 e Curves Equator na limpeza por EQ subtrativa.",
    tags: ["áudio", "behind the scenes"],
  },
  {
    cat: "tutoriais",
    title: "Color Correction for Concert Lighting - Fixing Extreme Color Tints in Adobe Lightroom",
    url: "https://www.youtube.com/watch?v=_R2cUv61s7I",
    description: "Workflow no Lightroom pra recuperar fotos de show com dominantes extremas de azul, magenta e vermelho sem cair no preto e branco. Usa White Balance, painel Calibration (Hue por canal primário), Color Grading e Color Mixer pra trazer skin tones e cores naturais de volta.",
    tags: ["color grading", "iluminação"],
  },
  {
    cat: "tutoriais",
    title: "The \"Geometry\" of Colours",
    url: "https://www.youtube.com/watch?v=7KYwi2F5Ce4",
    description: "Como a geometria dos espaços de cor define as relações entre cores. Uma perspectiva matemática e visual.",
    tags: ["color grading"],
  },
  {
    cat: "tutoriais",
    title: "Why The Bear Gets In Your Head",
    url: "https://www.youtube.com/watch?v=Lca_XEoO4b8",
    description: "Análise do que torna The Bear tão impactante: edição, direção e som trabalhando juntos de forma cirúrgica.",
    tags: ["análise", "edição", "direção"],
  },
  {
    cat: "tutoriais",
    title: "How To Get a Commercial Look In DaVinci Resolve",
    url: "https://www.youtube.com/watch?v=gZXIfcm2KR8",
    description: "Workflow completo para alcançar um look publicitário limpo e polido direto no DaVinci Resolve.",
    tags: ["davinci resolve", "color grading", "publicidade"],
  },
  {
    cat: "tutoriais",
    title: "How To Edit Documentaries like James Jani",
    url: "https://www.youtube.com/watch?v=bwz-jLZz2w8",
    description: "Como estruturar, narrar e editar documentários no estilo de James Jani: ritmo, storytelling e recursos visuais.",
    tags: ["edição", "documentário", "processo criativo"],
  },
  {
    cat: "processo",
    title: "DIREÇÃO DE FOTOGRAFIA EM PUBLICIDADE, CLIPES E FICÇÃO (feat. Victor Alencar)",
    url: "https://www.youtube.com/watch?v=x3s0kMgSiMY",
    description: "Conversa aprofundada sobre como a direção de fotografia se adapta a diferentes formatos audiovisuais com Victor Alencar.",
    tags: ["cinematografia", "direção", "entrevista"],
  },
  {
    cat: "tutoriais",
    title: "Why You Should Care About Lighting Ratios",
    url: "https://www.youtube.com/watch?v=U4egvCgW7qc",
    description: "Por que dominar ratios de iluminação muda completamente a qualidade e o controle sobre a sua imagem.",
    tags: ["iluminação", "cinematografia"],
  },
  {
    cat: "processo",
    title: "One-Man Videographer: How To Shoot, Price & Deliver a Corporate Video",
    url: "https://www.youtube.com/watch?v=NJBznivKoTg",
    description: "Como filmar, precificar e entregar vídeo corporativo trabalhando sozinho, do orçamento à entrega.",
    tags: ["carreira", "produção", "negócios"],
  },
  {
    cat: "processo",
    title: "How I Made Over $200,000 As A Filmmaker Last Year",
    url: "https://www.youtube.com/watch?v=n0Afhmb1-ag",
    description: "Relato detalhado de como um filmmaker independente faturou mais de $200k: fontes de renda, estratégias e mentalidade.",
    tags: ["carreira", "negócios"],
  },
  {
    cat: "processo",
    title: "\"This Was Expensive\" Commercial Breakdown With Oliver Millar",
    url: "https://www.youtube.com/watch?v=0hrsMdpWsBw",
    description: "O cinematógrafo Oliver Millar detalha os bastidores de um comercial de alto orçamento para a On Running com Zendaya. Iluminação com SkyPanel, Sony Venice, filosofia de set e carreira.",
    tags: ["análise", "cinematografia", "publicidade", "iluminação"],
  },
  {
    cat: "processo",
    title: "How IMAX 70MM Film is Projected!",
    url: "https://www.youtube.com/watch?v=7S_geBV5bLQ",
    description: "Adam Savage explora os bastidores da IMAX para mostrar o processo monumental de montar e projetar filmes em 70mm, dos rolos de centenas de quilos à cabine de projeção.",
    tags: ["cinematografia", "behind the scenes"],
  },
  {
    cat: "processo",
    title: "How IMAX 70MM Film is Scanned and Printed!",
    url: "https://www.youtube.com/watch?v=SYkAWTmpTBc",
    description: "Adam Savage visita a IMAX para entender como filmes 70mm são digitalizados e reimpresos em película, mostrando como analógico e digital coexistem no cinema de alta fidelidade.",
    tags: ["cinematografia", "behind the scenes"],
  },
  {
    cat: "tutoriais",
    title: "THE CLEANEST WAY To Grade Teal & Orange | Ozark Look",
    url: "https://www.youtube.com/watch?v=SnqE7UtEErU",
    description: "Danny Gan ensina a aplicar o visual teal & orange no estilo Ozark no DaVinci Resolve usando nós paralelos, sem qualifiers, sem máscaras, com proteção limpa dos tons de pele.",
    tags: ["davinci resolve", "color grading"],
  },
  {
    cat: "tutoriais",
    title: "Lighting spaces. Not faces!",
    url: "https://www.youtube.com/watch?v=ptyewwtjBpo",
    description: "Blaine Westropp defende iluminar o ambiente em vez do rosto: entender a motivação da luz no espaço resulta em imagens mais naturais, imersivas e cinematográficas.",
    tags: ["iluminação", "cinematografia"],
  },
  {
    cat: "processo",
    title: "Behind the Track: 'Manchild' by Sabrina Carpenter",
    url: "https://www.youtube.com/watch?v=FZCVYCS8x5M",
    description: "O produtor Jack Antonoff destrincha a produção de 'Manchild' na Mix with the Masters. Equipamentos vintage como instrumentos, ecos de fita, e a filosofia de deixar espaço na mixagem.",
    tags: ["áudio", "produção", "behind the scenes"],
  },
  {
    cat: "processo",
    title: "Why Christopher Nolan shot \"The Odyssey\" on IMAX film",
    url: "https://www.youtube.com/watch?v=1GEqDZ3hQSo",
    description: "Bastidores do filme de Christopher Nolan rodado inteiro em película IMAX. Invólucro à prova de som de 135kg, montagem manual no FotoKem e correção de cor fotoquímica tradicional.",
    tags: ["cinematografia", "análise", "behind the scenes"],
  },
  {
    cat: "processo",
    title: "How I Made Over $250,000 As A Filmmaker Last Year",
    url: "https://www.youtube.com/watch?v=MuXObj2ze9Y",
    description: "Análise financeira transparente de um cineasta: quanto entrou em cada frente (direção, fotografia, edição, renda passiva) e a diferença entre dias pagos e dias realmente trabalhados.",
    tags: ["carreira", "negócios"],
  },

  // ── Processo Criativo ────────────────────────────────────────
  {
    cat: "processo",
    title: "Eduardo Marinho - Vencer, vencer, vencer, para que",
    url: "https://www.youtube.com/watch?v=j72UPe2qnV4",
    description: "Eduardo Marinho reflete sobre o sentido real de vencer e o que de fato importa na jornada criativa.",
    tags: ["mindset", "processo criativo", "carreira"],
  },
  {
    cat: "processo",
    title: "Behind the Scenes of Lil Yachty's \"Murda\" Music Video",
    url: "https://www.youtube.com/watch?v=uGRfuxmK6ls",
    description: "Bastidores completos da produção do videoclipe 'Murda' de Lil Yachty: decisões criativas e de set.",
    tags: ["behind the scenes", "videoclipe", "produção", "processo criativo"],
  },
  {
    cat: "processo",
    title: "Observar e Absorver - Eduardo Marinho (Documentário Completo)",
    url: "https://www.youtube.com/watch?v=I7arqW5luKc",
    description: "Documentário completo de Eduardo Marinho sobre o ato de observar o mundo como combustível para a criatividade.",
    tags: ["documentário", "mindset", "processo criativo"],
  },
  {
    cat: "processo",
    title: "how i fixed my attention span",
    url: "https://www.youtube.com/watch?v=vYaNiC4kchg",
    description: "Como reconquistar foco e atenção em um mundo cheio de distrações. Estratégias práticas e honestas.",
    tags: ["mindset", "processo criativo"],
  },
  {
    cat: "processo",
    title: "Sobre terminar o que você começou",
    url: "https://www.youtube.com/watch?v=RH7VZVKTzac",
    description: "Reflexão sobre a importância de terminar o que se começa, e por que a maioria dos projetos criativos morre no meio.",
    tags: ["mindset", "processo criativo"],
  },
  {
    cat: "processo",
    title: "Navigating the Matrix",
    url: "https://www.youtube.com/watch?v=Pdp3p23P-TI",
    description: "Casey Neistat propõe uma reflexão sobre produtividade através de uma 'Matriz de Prioridades' dividida em quatro quadrantes, e por que fazer muito não significa realizar de verdade.",
    tags: ["mindset", "processo criativo", "carreira"],
  },
  {
    cat: "processo",
    title: "50 Mil Pessoas e UMA SONY FX3",
    url: "https://www.youtube.com/watch?v=jlXE2yOEBmQ",
    description: "Bastidores de cobrir um show de 50 mil pessoas com equipe enxuta e uma Sony FX3. Lentes, drone FPV, isolamento de áudio no Moises e preto e branco como recurso criativo.",
    tags: ["behind the scenes", "produção", "cinematografia"],
  },
  {
    cat: "processo",
    title: "GENER8ION - STORM (BTS) Starring Yung Lean",
    url: "https://www.youtube.com/watch?v=Xoi7reIF2r8",
    description: "Making-of do projeto STORM com Yung Lean, dirigido por Romain Gavras. A dinâmica do set, a narrativa por trás do clipe e a produção da coreografia de Damien Jalet.",
    tags: ["behind the scenes", "videoclipe"],
  },
  {
    cat: "processo",
    title: "Ed Hardy: the Godfather of Tattooing",
    url: "https://www.youtube.com/watch?v=Tm9GjI02CNo",
    description: "A trajetória de Ed Hardy transformando a tatuagem em arte fina. Customização, arquivo meticuloso, transmissão de conhecimento e a crença de que criar é a parte mais importante.",
    tags: ["documentário", "arte", "processo criativo"],
  },
  {
    cat: "processo",
    title: "Evanescence - Who Will You Follow - The Making Of",
    url: "https://www.youtube.com/watch?v=xWb-ZSx1IDw",
    description: "Amy Lee detalha a visão por trás do clipe dirigido por Jensen Noen. Conceito sobre redes sociais, atuar em velocidade dobrada para câmera lenta e 12 ratos treinados em cena.",
    tags: ["behind the scenes", "videoclipe", "direção"],
  },

  {
    cat: "processo",
    title: "EUROVISION SONG CONTEST 2026 • Behind the scenes • Production & Lighting Design",
    url: "https://www.youtube.com/watch?v=Oi-ItRJxFjw",
    description: "Cenógrafo, lighting designer e riggers contam como o limite de carga do teto virou um rig de 80 moving lights em winches cinéticos. Mostram também a rotina de programar 50 performances no grandMA3, dividindo o rig entre operadores e limpando luz plano a plano.",
    tags: ["behind the scenes","iluminação","produção","processo criativo"],
  },
  {
    cat: "processo",
    title: "Bad Bunny Behind the Scenes Super Bowl Halftime Show!",
    url: "https://www.youtube.com/watch?v=KDjATf-Ws5k",
    description: "Como a limitação de peso sobre o gramado matou o cenário em carros e virou 386 pessoas fantasiadas de cana e bananeira. Mostra também o ensaio offsite com os operadores de câmera reais e a montagem do palco inteiro em 8 minutos.",
    tags: ["behind the scenes","produção","direção","processo criativo"],
  },
  {
    cat: "processo",
    title: "Why divergent thinkers beat geniuses in the real world | David Epstein",
    url: "https://www.youtube.com/watch?v=Js4NiTFq9Pw",
    description: "David Epstein defende que amplitude ganha da especialização precoce em áreas instáveis, onde regra e feedback mudam. Usa Gunpei Yokoi, que criou o Game Boy juntando tecnologias baratas e já ultrapassadas, e fecha com uma ideia simples: compare seu trabalho com o de ontem.",
    tags: ["mindset","carreira","processo criativo","entrevista"],
  },
  {
    cat: "processo",
    title: "Why The Tonight Show is so hard to mix",
    url: "https://www.youtube.com/watch?v=emq2nevl898",
    description: "Fred Zeller, mixer de produção do Tonight Show e dos 15 anos de Conan, abre a sala de controle: 24 mics sem fio, lavs na plateia pra pegar a risada isolada, DADpad pros efeitos e por que ele prefere andar no fader do Jimmy a comprimir tudo.",
    tags: ["áudio","behind the scenes","produção","entrevista"],
  },
  {
    cat: "processo",
    title: "What if it actually works out?",
    url: "https://www.youtube.com/watch?v=5aR-5cNABAI",
    description: "Stan Lee conta que o editor rejeitou o Homem-Aranha por ser aranha, adolescente e cheio de problemas pessoais. Ele enfiou o personagem na última edição de uma revista que já ia morrer. O recado, se a ideia é sua e você acredita nela, não deixe ninguém te convencer a largar.",
    tags: ["mindset","processo criativo","carreira"],
  },
  {
    cat: "processo",
    title: "the best piece of advice I've ever received",
    url: "https://www.youtube.com/watch?v=Yrug2Fd9CWY",
    description: "Ensaio sobre a ideia dos 2% do livro The Comfort Crisis: só 2% das pessoas pegam a escada quando tem elevador do lado. O argumento central é consistência acima de intensidade, porque hábito pequeno vira identidade e meta grande vira prazo que você fura em fevereiro.",
    tags: ["mindset","processo criativo"],
  },
  {
    cat: "processo",
    title: "O vídeo que vai curar a sua PROCRASTINAÇÃO",
    url: "https://www.youtube.com/watch?v=dh64bHIhbiU",
    description: "Gabriel Saab argumenta que procrastinar é fuga emocional, não preguiça, e que trabalho criativo tem centenas de microdecisões que disparam esse escape. Propõe reduzir a fricção da tarefa, aumentar a dos gatilhos e trocar comportamento por identidade.",
    tags: ["mindset","processo criativo","carreira"],
  },
  {
    cat: "processo",
    title: "stop being an audience member of your own life",
    url: "https://www.youtube.com/watch?v=13yIfxczLpc",
    description: "Ela mede 4h30 de tela por dia e percebe listas infinitas de ideias salvas que nunca viraram nada, então força a mão: pinta, testa gouache, recria um plano que viu no Instagram. O insight, se você nunca se permite ser iniciante, nunca deixa de ser um.",
    tags: ["mindset","processo criativo"],
  },
  {
    cat: "processo",
    title: "Por que pessoas BURRAS se acham INTELIGENTES?",
    url: "https://www.youtube.com/watch?v=0TjhggXdj-A",
    description: "Pedro Loos destrincha o efeito Dunning-Kruger pela curva de confiança versus conhecimento, incluindo o fundo do poço onde mora a síndrome do impostor. Fecha com o paradoxo de Polanyi, a ideia de que sabemos mais do que conseguimos explicar, e o limite que isso impõe à IA.",
    tags: ["mindset","carreira","processo criativo"],
  },
  {
    cat: "processo",
    title: "I Became a Teacher for a Day. Big Mistake",
    url: "https://www.youtube.com/watch?v=k4sOrwMcOXc",
    description: "Ludwig dá aula pra criadores iniciantes sobre funil de conteúdo, com números reais de uma live de 6 horas que virou VODs, vídeo longo e shorts. Defende gravar menos, reservar horas do dia pra ideação e tratar cada transmissão como matéria-prima de outros formatos.",
    tags: ["carreira","negócios","mindset","processo criativo"],
  },
  {
    cat: "processo",
    title: "We went to see where film is made! Kodak Rochester Factory Tour",
    url: "https://www.youtube.com/watch?v=u_o8kpY7EEs",
    description: "Três dias dentro da fábrica da Kodak, do pellet de poliéster ao corte e perfuração no escuro, tudo gravado em 35mm e 16mm. Termina com entrevistas sobre sucessão de conhecimento, o estoque finito de câmeras usadas e por que o filme voltou a crescer.",
    tags: ["documentário","behind the scenes","cinematografia","produção"],
  },
  {
    cat: "processo",
    title: "Being a Projectionist for The Odyssey in 70mm",
    url: "https://www.youtube.com/watch?v=tN05nzk9oT8",
    description: "Bastidores da montagem da cópia 70mm da Odisseia rolo a rolo, o tech check às 5 da manhã e a paranoia de não riscar o filme, já que risco em película é permanente. Fecha com a real: não existe escola nem trilha de formação pra virar projecionista hoje.",
    tags: ["behind the scenes","carreira","produção"],
  },

];
