// ============================================================
//  RESOURCES — embaralhados a cada visita.
//
//  Categorias: "referencias" | "tutoriais" | "processo"
//  Tipo: auto-detectado pela URL (YouTube = vídeo, resto = link)
//        Para imagens ou downloads, adicione: type: "image" | "download"
//
//  Para adicionar novos recursos, cole aqui no array abaixo.
// ============================================================

const RESOURCES = [

  // ── Referências ──────────────────────────────────────────────
  {
    cat: "referencias",
    title: "Lay's Chip Cam with David Beckham & Thierry Henry",
    url: "https://www.youtube.com/watch?v=LLJ38OdS_q8",
    description: "Comercial da Lay's no estádio com Beckham e Thierry Henry quebrando a quarta parede pra falar com a câmera. Vale pela comédia improvisada, timing de reação e como a campanha integra naturalidade de celebridade e cena de torcida.",
    tags: ["publicidade", "direção"],
  },
  {
    cat: "referencias",
    title: "Defy — On Spec Ad (Sony Venice + FX3 + Freefly Ember)",
    url: "https://www.youtube.com/watch?v=w0PkvfJ-uBg",
    description: "Spec ad de 30s da Tenfold para a On, rodado em 1 dia com Sony Venice, FX3 e drone Freefly Ember nas Cooke S4. Referência de comercial esportivo: ritmo, movimento de câmera e textura de imagem.",
    tags: ["publicidade", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "ArrDee — Different ft. The Shapeshifters",
    url: "https://www.youtube.com/watch?v=6meAaX907to",
    description: "Videoclipe do rapper britânico ArrDee em parceria com The Shapeshifters. Produção visual densa e bem construída.",
    tags: ["videoclipe", "direção"],
  },
  {
    cat: "processo",
    title: "Como produzimos 4 Reels para um restaurante em 1 dia só",
    url: "https://www.youtube.com/watch?v=T70A0yeBNLU",
    description: "Produção acelerada de conteúdo: como planejar e executar 4 reels para um cliente em um único dia de gravação.",
    tags: ["produção", "behind the scenes", "processo criativo"],
  },
  {
    cat: "referencias",
    title: "Cinematic Fashion Film — Beyond Space (Sony Venice + Leica R)",
    url: "https://www.youtube.com/watch?v=xKha-MXPKTQ",
    description: "Fashion film cinematográfico com combinação de Sony Venice e lentes Leica R. Estética limpa e atmosfera forte.",
    tags: ["fashion film", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "Sempre Forza Ferrari",
    url: "https://www.youtube.com/watch?v=rvpD9e-wPBk",
    description: "Filme de marca da Ferrari na F1, montagem rápida no ritmo da paixão dos pilotos. Vale pela direção cinematográfica, color em torno do vermelho e edição que costura depoimento e ação de pista.",
    tags: ["publicidade", "direção", "edição"],
  },
  {
    cat: "referencias",
    title: "Young Miko — WASSUP (Official)",
    url: "https://www.youtube.com/watch?v=LEhTlLnOVDU",
    description: "Videoclipe oficial de Young Miko. Visual arrojado com referências de estética latina contemporânea.",
    tags: ["videoclipe", "direção"],
  },
  {
    cat: "referencias",
    title: "NEMZZZ — PTSD (Official Video)",
    url: "https://www.youtube.com/watch?v=oojBNXKtE9M",
    description: "Videoclipe oficial do NEMZZZ pra faixa PTSD, do mixtape Do Not Disturb. Vale assistir como referência de direção e estética de clipe de rap UK em formato curto, pouco mais de 2 minutos.",
    tags: ["videoclipe", "direção", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "Kidwild — Redemption ft. Nemzzz",
    url: "https://www.youtube.com/watch?v=MYHrk_6qky8",
    description: "Videoclipe de rap UK dirigido por donprod e dinperlis. Vale como referência de direção e iluminação em locação, com styling cuidado e visual coeso pra peça curta de 2:37.",
    tags: ["videoclipe", "direção", "iluminação"],
  },
  {
    cat: "referencias",
    title: "The Next Chapter — First US Female Fitness Athlete of Red Bull",
    url: "https://www.youtube.com/watch?v=i0KBwYzivmc",
    description: "Atleta de fitness da Red Bull conta em primeira pessoa como a pressão por ranking virou crise de saúde mental, a pausa de um ano e o reencontro com o esporte. Vale pela perspectiva sobre carreira e propósito.",
    tags: ["documentário", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "Interplanetary Criminal — No Time feat. Sadboi (Official Video)",
    url: "https://www.youtube.com/watch?v=XVzxU5HNwtk",
    description: "Videoclipe oficial com estética visual marcante, na linha dos outros UK artists da coleção.",
    tags: ["videoclipe", "direção"],
  },
  {
    cat: "referencias",
    title: "adidas — Where There's a Pitch, There's a Legend",
    url: "https://www.youtube.com/watch?v=mJJY53qhJe0",
    description: "Curta de 5 min que conta um 3 contra 3 de rua como lenda urbana, narrada no carro a caminho do jogo. Vale pelo roteiro cômico, ritmo de diálogo e direção de elenco com Chalamet, Messi, Bellingham, Lamine Yamal e Trinity Rodman.",
    tags: ["publicidade", "direção", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "Chasing Sub 2 — Maratona Sub 2h (adidas)",
    url: "https://www.youtube.com/watch?v=qRr0lmYvp5g",
    description: "Filme de marca da adidas sobre Sabastian Sawe quebrando as 2h na maratona de Londres 2026. Vale pela fotografia, ritmo de montagem e construção emocional de um doc esportivo de orçamento alto, dos bastidores íntimos ao clímax da prova.",
    tags: ["documentário", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "Ibeyi — Aset (Official Video)",
    url: "https://www.youtube.com/watch?v=XwxA_oOzMDY",
    description: "Clipe da Ibeyi rodado em Cuba por Corry Van Rhijn e Roman Pichon Herrera, fotografia de Luis Armando Arteaga. Vale pela direção que mistura percussão e dança ao vivo com pipeline pesado de VFX e arte em IA. Referência de integração entre captação real e pós.",
    tags: ["videoclipe", "cinematografia"],
  },
  {
    cat: "referencias",
    title: "GENER8ION — STORM ft. Yung Lean (dir. Romain Gavras)",
    url: "https://www.youtube.com/watch?v=x6_mbnsh6VU",
    description: "Videoclipe experimental dirigido por Romain Gavras com coreografia de Damien Jalet. Atmosfera distópica, coreografia coletiva intensa, cinematografia impecável.",
    tags: ["videoclipe", "cinematografia", "direção"],
  },

  // ── Tutoriais ────────────────────────────────────────────────
  {
    cat: "tutoriais",
    title: "How to Animate Maps Like VOX — After Effects Tutorial",
    url: "https://www.youtube.com/watch?v=8Xxxd7me-oc",
    description: "Monta uma animação de mapa estilo VOX no After Effects com um rig de câmera 3D controlado por nulls (controllers de rotação X, Y, Z e posição via pick-whip parenting), além de profundidade de campo com abertura alta, renderer 3D clássico e motion blur.",
    tags: ["after effects", "motion design"],
  },
  {
    cat: "tutoriais",
    title: "A Simple Guide to Depth of Field",
    url: "https://www.youtube.com/watch?v=34jkJoN8qOI",
    description: "Explica profundidade de campo do zero e os três controles práticos: distância até o sujeito, distância focal e abertura (f-stop). Mostra como cada um abre ou fecha o foco e a lógica invertida da escala de f-stop.",
    tags: ["cinematografia"],
  },
  {
    cat: "tutoriais",
    title: "What is Dynamic Range? — Video Tech Explained",
    url: "https://www.youtube.com/watch?v=FTXMx8ij_Nw",
    description: "Explica o que define o alcance dinâmico do sensor: full well capacity e noise floor, por que os stops úteis variam entre RED e ARRI, como a curva gama (log vs padrão) limita a imagem final e por que ISO nativo importa fora do RAW.",
    tags: ["cinematografia"],
  },
  {
    cat: "tutoriais",
    title: "Color Spaces: Explained from the Ground Up",
    url: "https://www.youtube.com/watch?v=99v96TL-tuY",
    description: "Explica espaço de cor do zero: o que é cor, metamerismo, como os cones LMS viram o CIE 1931 XYZ, e por que Rec.709, DCI-P3 e Rec.2020 são RGB absolutos que só mudam os pontos primários. Bom pra entender o que rola por baixo do color grading.",
    tags: ["color grading"],
  },
  {
    cat: "tutoriais",
    title: "Color Theory — SULA LIVES",
    url: "https://www.youtube.com/watch?v=VbJtLQPj4go",
    description: "Introdução à teoria da cor pra pintura digital: os três atributos (valor, matiz, saturação), o círculo cromático como simplificação de um espaço 3D, cores complementares, mistura de pigmento vs navegação digital e o gamut mask do James Gurney.",
    tags: ["color grading"],
  },
  {
    cat: "tutoriais",
    title: "The Amazing Math Behind Colors!",
    url: "https://www.youtube.com/watch?v=gnUYoQ1pwes",
    description: "Explica a ciência da cor do zero: resposta dos cones, espaços LMS e CIE 1931, diagrama de cromaticidade, gamut, cubo RGB, conversão pra HSV e hex, e como telas RGB e impressoras CMYK formam cada cor.",
    tags: ["color grading"],
  },
  {
    cat: "tutoriais",
    title: "Hide Your Audio Cuts With This Method in DaVinci Resolve",
    url: "https://www.youtube.com/watch?v=d2RRrqNzmWg",
    description: "Como cortar áudio de entrevista nas consoantes surdas (p, t, k, s, f), que não têm pitch e soam sempre iguais, pra emendas invisíveis. Inclui o truque de defasar o corte de vídeo do corte de áudio pra esconder a junção. Serve em qualquer editor.",
    tags: ["davinci resolve", "áudio", "edição"],
  },
  {
    cat: "processo",
    title: "How the 'Severance' Editor Cut the Finale Like a Music Video",
    url: "https://www.youtube.com/watch?v=eGkfByNEcw0",
    description: "Geoffrey Richman destrincha decisões de montagem do finale de Severance: empilhar takes em tracks paralelos pra comparar selects, usar a banda marcial como trilha contínua, construir ritmo com cortes rápidos e parada seca, e deslocar o POV pra emoção ficar só no Mark.",
    tags: ["análise", "edição", "behind the scenes"],
  },
  {
    cat: "tutoriais",
    title: "Beat the Compression! How to Get Better YouTube Uploads",
    url: "https://www.youtube.com/watch?v=DI1BjkmVhTg",
    description: "Gerald Undone testa o que sobrevive à compressão do YouTube: super-sharpen leve no export, H.264 em vez de H.265/AV1, MP4, bitrate variável até 45 Mbps em 4K, sem quantizer (Constant QP), e evitar gradientes escuros e cenas dark.",
    tags: ["produção", "edição"],
  },
  {
    cat: "tutoriais",
    title: "Mastering Skin Tones with Balance DCTL for DaVinci Resolve",
    url: "https://www.youtube.com/watch?v=_wpinhILzgg",
    description: "Walkthrough do Balance DCTL (Utility DCTL pack do Mononodes) no DaVinci Resolve: indicador de tom de pele que marca desvios em magenta/verde, slider de ângulo de matiz, mapas de calor de exposição e saturação, e o botão gray out non-skin para focar na pele.",
    tags: ["davinci resolve", "color grading"],
  },
  {
    cat: "processo",
    title: "Inside the Live Session: Billie Eilish — 'Birds of a Feather' com Aron Forbes",
    url: "https://www.youtube.com/watch?v=5CgR3UH1txU",
    description: "Aron Forbes destrincha o mix da vocal ao vivo da Billie Eilish e mostra cada plugin Waves no trabalho: Clarity Vx pra matar o vazamento da bateria no microfone, C4 multibanda pra encaixar os backing vocals atrás dela, S1 pra alargar as harmonias e F6 e Curves Equator na limpeza por EQ subtrativa.",
    tags: ["áudio", "behind the scenes"],
  },
  {
    cat: "tutoriais",
    title: "Color Correction for Concert Lighting — Fixing Extreme Tints in Lightroom",
    url: "https://www.youtube.com/watch?v=_R2cUv61s7I",
    description: "Workflow no Lightroom pra recuperar fotos de show com dominantes extremas de azul, magenta e vermelho sem cair no preto e branco. Usa White Balance, painel Calibration (Hue por canal primário), Color Grading e Color Mixer pra trazer skin tones e cores naturais de volta.",
    tags: ["color grading", "iluminação"],
  },
  {
    cat: "tutoriais",
    title: "The \"Geometry\" of Colours",
    url: "https://www.youtube.com/watch?v=7KYwi2F5Ce4",
    description: "Como a geometria dos espaços de cor define as relações entre cores. Uma perspectiva matemática e visual.",
    tags: ["color grading"],
  },
  {
    cat: "tutoriais",
    title: "Why The Bear Gets In Your Head",
    url: "https://www.youtube.com/watch?v=Lca_XEoO4b8",
    description: "Análise do que torna The Bear tão impactante: edição, direção e som trabalhando juntos de forma cirúrgica.",
    tags: ["análise", "edição", "direção"],
  },
  {
    cat: "tutoriais",
    title: "How To Get a Commercial Look in DaVinci Resolve",
    url: "https://www.youtube.com/watch?v=gZXIfcm2KR8",
    description: "Workflow completo para alcançar um look publicitário limpo e polido direto no DaVinci Resolve.",
    tags: ["davinci resolve", "color grading", "publicidade"],
  },
  {
    cat: "tutoriais",
    title: "How To Edit Documentaries Like James Jani",
    url: "https://www.youtube.com/watch?v=bwz-jLZz2w8",
    description: "Como estruturar, narrar e editar documentários no estilo de James Jani: ritmo, storytelling e recursos visuais.",
    tags: ["edição", "documentário", "processo criativo"],
  },
  {
    cat: "processo",
    title: "Direção de Fotografia em Publicidade, Clipes e Ficção — feat. Victor Alencar",
    url: "https://www.youtube.com/watch?v=x3s0kMgSiMY",
    description: "Conversa aprofundada sobre como a direção de fotografia se adapta a diferentes formatos audiovisuais com Victor Alencar.",
    tags: ["cinematografia", "direção", "entrevista"],
  },
  {
    cat: "tutoriais",
    title: "Why You Should Care About Lighting Ratios",
    url: "https://www.youtube.com/watch?v=U4egvCgW7qc",
    description: "Por que dominar ratios de iluminação muda completamente a qualidade e o controle sobre a sua imagem.",
    tags: ["iluminação", "cinematografia"],
  },
  {
    cat: "processo",
    title: "One-Man Videographer: How to Shoot, Price & Deliver a Corporate Video",
    url: "https://www.youtube.com/watch?v=NJBznivKoTg",
    description: "Como filmar, precificar e entregar vídeo corporativo trabalhando sozinho, do orçamento à entrega.",
    tags: ["carreira", "produção", "negócios"],
  },
  {
    cat: "processo",
    title: "How I Made Over $200,000 As a Filmmaker Last Year",
    url: "https://www.youtube.com/watch?v=n0Afhmb1-ag",
    description: "Relato detalhado de como um filmmaker independente faturou mais de $200k: fontes de renda, estratégias e mentalidade.",
    tags: ["carreira", "negócios"],
  },
  {
    cat: "processo",
    title: "\"This Was Expensive\" — Commercial Breakdown with Oliver Millar",
    url: "https://www.youtube.com/watch?v=0hrsMdpWsBw",
    description: "O cinematógrafo Oliver Millar detalha os bastidores de um comercial de alto orçamento para a On Running com Zendaya. Iluminação com SkyPanel, Sony Venice, filosofia de set e carreira.",
    tags: ["análise", "cinematografia", "publicidade", "iluminação"],
  },
  {
    cat: "processo",
    title: "How IMAX 70MM Film is Projected!",
    url: "https://www.youtube.com/watch?v=7S_geBV5bLQ",
    description: "Adam Savage explora os bastidores da IMAX para mostrar o processo monumental de montar e projetar filmes em 70mm, dos rolos de centenas de quilos à cabine de projeção.",
    tags: ["cinematografia", "behind the scenes"],
  },
  {
    cat: "processo",
    title: "How IMAX 70MM Film is Scanned and Printed!",
    url: "https://www.youtube.com/watch?v=SYkAWTmpTBc",
    description: "Adam Savage visita a IMAX para entender como filmes 70mm são digitalizados e reimpresos em película, mostrando como analógico e digital coexistem no cinema de alta fidelidade.",
    tags: ["cinematografia", "behind the scenes"],
  },
  {
    cat: "tutoriais",
    title: "THE CLEANEST WAY To Grade Teal & Orange — Ozark Look",
    url: "https://www.youtube.com/watch?v=SnqE7UtEErU",
    description: "Danny Gan ensina a aplicar o visual teal & orange no estilo Ozark no DaVinci Resolve usando nós paralelos, sem qualifiers, sem máscaras, com proteção limpa dos tons de pele.",
    tags: ["davinci resolve", "color grading"],
  },
  {
    cat: "tutoriais",
    title: "Lighting Spaces. Not Faces!",
    url: "https://www.youtube.com/watch?v=ptyewwtjBpo",
    description: "Blaine Westropp defende iluminar o ambiente em vez do rosto: entender a motivação da luz no espaço resulta em imagens mais naturais, imersivas e cinematográficas.",
    tags: ["iluminação", "cinematografia"],
  },
  {
    cat: "processo",
    title: "Jack Antonoff Behind the Track — 'Manchild' (Sabrina Carpenter)",
    url: "https://www.youtube.com/watch?v=FZCVYCS8x5M",
    description: "O produtor Jack Antonoff destrincha a produção de 'Manchild' na Mix with the Masters. Equipamentos vintage como instrumentos, ecos de fita, e a filosofia de deixar espaço na mixagem.",
    tags: ["áudio", "produção", "behind the scenes"],
  },
  {
    cat: "processo",
    title: "The Odyssey — Primeiro Filme 100% em IMAX 70mm (Nolan)",
    url: "https://www.youtube.com/watch?v=1GEqDZ3hQSo",
    description: "Bastidores do filme de Christopher Nolan rodado inteiro em película IMAX. Invólucro à prova de som de 135kg, montagem manual no FotoKem e correção de cor fotoquímica tradicional.",
    tags: ["cinematografia", "análise", "behind the scenes"],
  },
  {
    cat: "tutoriais",
    title: "Quanto Ganhei Como Cineasta em 2026 — Scott Peters",
    url: "https://www.youtube.com/watch?v=MuXObj2ze9Y",
    description: "Análise financeira transparente de um cineasta: £286k faturados, divididos entre direção, fotografia, edição e renda passiva. Honestidade sobre dias trabalhados vs. dias reais.",
    tags: ["carreira", "negócios"],
  },

  // ── Processo Criativo ────────────────────────────────────────
  {
    cat: "processo",
    title: "Eduardo Marinho — Vencer, vencer, vencer, para quê?",
    url: "https://www.youtube.com/watch?v=j72UPe2qnV4",
    description: "Eduardo Marinho reflete sobre o sentido real de vencer e o que de fato importa na jornada criativa.",
    tags: ["mindset", "processo criativo", "carreira"],
  },
  {
    cat: "processo",
    title: "Behind the Scenes of Lil Yachty's \"Murda\" Music Video",
    url: "https://www.youtube.com/watch?v=uGRfuxmK6ls",
    description: "Bastidores completos da produção do videoclipe 'Murda' de Lil Yachty: decisões criativas e de set.",
    tags: ["behind the scenes", "videoclipe", "produção", "processo criativo"],
  },
  {
    cat: "processo",
    title: "Observar e Absorver — Eduardo Marinho (Documentário Completo)",
    url: "https://www.youtube.com/watch?v=I7arqW5luKc",
    description: "Documentário completo de Eduardo Marinho sobre o ato de observar o mundo como combustível para a criatividade.",
    tags: ["documentário", "mindset", "processo criativo"],
  },
  {
    cat: "processo",
    title: "How I Fixed My Attention Span",
    url: "https://www.youtube.com/watch?v=vYaNiC4kchg",
    description: "Como reconquistar foco e atenção em um mundo cheio de distrações. Estratégias práticas e honestas.",
    tags: ["mindset", "processo criativo"],
  },
  {
    cat: "processo",
    title: "About Finishing What You Started",
    url: "https://www.youtube.com/watch?v=RH7VZVKTzac",
    description: "Reflexão sobre a importância de terminar o que se começa, e por que a maioria dos projetos criativos morre no meio.",
    tags: ["mindset", "processo criativo"],
  },
  {
    cat: "processo",
    title: "Navigating the Matrix",
    url: "https://www.youtube.com/watch?v=Pdp3p23P-TI",
    description: "Casey Neistat propõe uma reflexão sobre produtividade através de uma 'Matriz de Prioridades' dividida em quatro quadrantes, e por que fazer muito não significa realizar de verdade.",
    tags: ["mindset", "processo criativo", "carreira"],
  },
  {
    cat: "processo",
    title: "Aftermovie Dominguinho no Allianz com 1 Câmera — Sand Filmes",
    url: "https://www.youtube.com/watch?v=jlXE2yOEBmQ",
    description: "Bastidores de cobrir um show de 50 mil pessoas com equipe enxuta e uma Sony FX3. Lentes, drone FPV, isolamento de áudio no Moises e preto e branco como recurso criativo.",
    tags: ["behind the scenes", "produção", "cinematografia"],
  },
  {
    cat: "processo",
    title: "GENER8ION STORM I & II — Behind the Scenes",
    url: "https://www.youtube.com/watch?v=Xoi7reIF2r8",
    description: "Making-of do projeto STORM com Yung Lean, dirigido por Romain Gavras. A dinâmica do set, a narrativa por trás do clipe e a produção da coreografia de Damien Jalet.",
    tags: ["behind the scenes", "videoclipe"],
  },
  {
    cat: "processo",
    title: "Ed Hardy — O Padrinho da Tatuagem Moderna",
    url: "https://www.youtube.com/watch?v=Tm9GjI02CNo",
    description: "A trajetória de Ed Hardy transformando a tatuagem em arte fina. Customização, arquivo meticuloso, transmissão de conhecimento e a crença de que criar é a parte mais importante.",
    tags: ["documentário", "arte", "processo criativo"],
  },
  {
    cat: "processo",
    title: "Evanescence — Who Will You Follow (Making Of)",
    url: "https://www.youtube.com/watch?v=xWb-ZSx1IDw",
    description: "Amy Lee detalha a visão por trás do clipe dirigido por Jensen Noen. Conceito sobre redes sociais, atuar em velocidade dobrada para câmera lenta e 12 ratos treinados em cena.",
    tags: ["behind the scenes", "videoclipe", "direção"],
  },

];
